// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source : proto/collection/orm/condition.proto
// #nullable enable
#nullable disable
namespace Guru.Collection.Orm
{
    /// <summary>
    /// 单值操作符
    /// </summary>
    public enum OperatorType
    {
        /// <summary>
        /// 等于
        /// </summary>
        EQ = 0,
        /// <summary>
        /// 不等于
        /// </summary>
        NE = 1,
        /// <summary>
        /// 大于
        /// </summary>
        GT = 2,
        /// <summary>
        /// 大于等于
        /// </summary>
        GTE = 3,
        /// <summary>
        /// 小于
        /// </summary>
        LT = 4,
        /// <summary>
        /// 小于等于
        /// </summary>
        LTE = 5,
        /// <summary>
        /// Like 类似
        /// </summary>
        LIKE = 6,
        /// <summary>
        /// Not Like 不类似
        /// </summary>
        NOT_LIKE = 7,
        /// <summary>
        /// Is Null 没有值
        /// </summary>
        NULL = 8,
        /// <summary>
        /// Is Not Null 有值
        /// </summary>
        NOT_NULL = 9
    }
    /// <summary>
    /// 多值操作符
    /// </summary>
    public enum MultiType
    {
        /// <summary>
        /// 非多值操作
        /// </summary>
        NO_MULTI = 0,
        /// <summary>
        /// Between 在 ... 之间
        /// </summary>
        BETWEEN = 1,
        /// <summary>
        /// Not Between 不在 ... 之间
        /// </summary>
        NOT_BETWEEN = 2,
        /// <summary>
        /// In 在 ... 之中
        /// </summary>
        IN = 3,
        /// <summary>
        /// Not In 不在 ... 之中
        /// </summary>
        NOT_IN = 4
    }
    /// <summary>
    /// 模糊查询规则
    /// </summary>
    public enum WildcardType
    {
        /// <summary>
        /// 非模糊查询
        /// </summary>
        NO_WILDCARD = 0,
        /// <summary>
        /// 包含特定字符串
        /// </summary>
        CONTAINS = 1,
        /// <summary>
        /// 已特定字符串开头
        /// </summary>
        STARTS_WITH = 2,
        /// <summary>
        /// 已特定字符串结尾
        /// </summary>
        ENDS_WITH = 3
    }
    /// <summary>
    /// 查询条件
    /// </summary>
    public class Condition 
    {
        /// <summary>
        /// 单值操作符
        /// </summary>  
        public OperatorType operatorType { get; set; }
        /// <summary>
        /// 多值操作符
        /// </summary>  
        public MultiType multi { get; set; }
        /// <summary>
        /// 模糊查询规则
        /// </summary>  
        public WildcardType wildcard { get; set; }
        /// <summary>
        /// 查询值
        /// </summary>  
        public Object value { get; set; }
    }
    /// <summary>
    /// 查询表达式
    /// </summary>
    public class PropertyFilter 
    {
        /// <summary>
        /// 字段名
        /// </summary>  
        public string property { get; set; }
        /// <summary>
        /// 查询条件
        /// </summary>  
        public Condition condition { get; set; }
    }
}