// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source : proto/collection/orm/query.proto
// #nullable enable
#nullable disable
namespace Guru.Collection.Orm
{
    /// <summary>
    /// 排序方向
    /// </summary>
    public enum SortDirection
    {
        ASC = 0,
        DESC = 1
    }
    /// <summary>
    /// 排序参数
    /// </summary>
    public class SortParam 
    {
        /// <summary>
        /// 要排序的字段/属性名，暂不支持嵌套
        /// </summary>  
        public string property { get; set; }
        /// <summary>
        /// 排序方向
        /// </summary>  
        public SortDirection direction { get; set; }
    }
    /// <summary>
    /// 分页和排序的请求
    /// </summary>
    public class PageRequest 
    {
        /// <summary>
        /// 请求的页码，从1开始
        /// </summary>  
        public long number { get; set; }
        /// <summary>
        /// 请求的每页记录数
        /// </summary>  
        public long size { get; set; }
        /// <summary>
        /// 请求使用的排序参数列表，排在前面的排序参数优先级更高
        /// </summary>  
        public IList<SortParam> sorts { get; set; }
    }
    /// <summary>
    /// 查询返回的分页信息
    /// </summary>
    public class PageInfo 
    {
        /// <summary>
        /// 当前实际页码。如果记录集不为空，页码从1开始；如果记录集为空，页码为0。可能和翻页请求设定的给定页码不同。
        /// </summary>  
        public long number { get; set; }
        /// <summary>
        /// 每页最多容纳记录数，由翻页请求设定。注意：可能比本页实际记录数 NumberOfElements 要大
        /// </summary>  
        public long size { get; set; }
        /// <summary>
        /// 本页第一条记录在整个记录集中的偏移量，由翻页请求（给定页码、每页最大记录数）、记录集记录总数共同决定
        /// </summary>  
        public long offset { get; set; }
        /// <summary>
        /// 本页实际记录数
        /// </summary>  
        public long numberOfElements { get; set; }
        /// <summary>
        /// 记录集总条数。即：在不翻页的情况下，满足请求条件的所有记录条数
        /// </summary>  
        public long totalElements { get; set; }
        /// <summary>
        /// 总页数。即：满足请求条件的所有记录，按翻页请求中的每页最大记录数分页，分布在多少页上
        /// </summary>  
        public long totalPages { get; set; }
        /// <summary>
        /// 当前页是否为第一页
        /// </summary>  
        public bool first { get; set; }
        /// <summary>
        /// 当前页是否为最后一页
        /// </summary>  
        public bool last { get; set; }
        /// <summary>
        /// 翻页请求的排序条件
        /// </summary>  
        public IList<SortParam> sorts { get; set; }
    }
}